"""Creates animal, zookeeper, and enclosure models

Revision ID: 70d0db6e7fa5
Revises: 0b6f632146d9
Create Date: 2023-04-04 12:19:59.265313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d0db6e7fa5'
down_revision = '0b6f632146d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('open_to_visitors', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zookeepers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('zookeeper', sa.Integer(), nullable=True),
    sa.Column('enclosure', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enclosure'], ['enclosures.id'], name=op.f('fk_animals_enclosure_enclosures')),
    sa.ForeignKeyConstraint(['zookeeper'], ['zookeepers.id'], name=op.f('fk_animals_zookeeper_zookeepers')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animals')
    op.drop_table('zookeepers')
    op.drop_table('enclosures')
    # ### end Alembic commands ###
