"""Revises animals model column names

Revision ID: 8ae25aed787e
Revises: 70d0db6e7fa5
Create Date: 2023-04-04 12:25:45.918394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae25aed787e'
down_revision = '70d0db6e7fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zookeeper_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('enclosure_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_animals_zookeeper_zookeepers', type_='foreignkey')
        batch_op.drop_constraint('fk_animals_enclosure_enclosures', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_animals_zookeeper_id_zookeepers'), 'zookeepers', ['zookeeper_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_animals_enclosure_id_enclosures'), 'enclosures', ['enclosure_id'], ['id'])
        batch_op.drop_column('enclosure')
        batch_op.drop_column('zookeeper')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zookeeper', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('enclosure', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_animals_enclosure_id_enclosures'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_animals_zookeeper_id_zookeepers'), type_='foreignkey')
        batch_op.create_foreign_key('fk_animals_enclosure_enclosures', 'enclosures', ['enclosure'], ['id'])
        batch_op.create_foreign_key('fk_animals_zookeeper_zookeepers', 'zookeepers', ['zookeeper'], ['id'])
        batch_op.drop_column('enclosure_id')
        batch_op.drop_column('zookeeper_id')

    # ### end Alembic commands ###
